version: '3.4'
services:
    postgresql:
      image: postgres:11.12
      env_file:
        - ./env/.postgresql
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
    # redis:
    #   restart: always
    #   image: redis:6.2.3
    #   volumes:
    #     - redis-data:/data
    nginx:
      restart: always
      image: nginx:1.20.0
      env_file:
        - ./env/.env
      volumes:
        - ./spinach/static:/spinach/spinach/static
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - target: "8000"
          published: "8000"
          mode: host
        - target: "80"
          published: "80"
          mode: host
    spinach:
      image: chalice/spinach:latest
      build: ./spinach
      restart: always
      env_file:
        - ./env/.env
        - ./env/.postgresql

      volumes:
        - ./spinach:/app/
      depends_on:
        - postgresql

volumes:
    mysqldata:
    # redis-data: